config/routes.rb
DbcPower::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  resources :users
  resources :students
  resources :cohorts
  root to: "home#index"

  get '/comment_vote', to: 'students#comment_vote'

get '/logout', to: 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :student
  validates :body, length: { minimum: 15 }
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :comments
  include Gravtastic
  gravtastic

   before_save :default_value

    def upvote
        self.student_points += 1
    end


    private

    def default_value
      self.student_points ||= 0
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # before_save :default_values
  before_save :stock_votes
  has_many :comments


  def stock_votes
    self.votes_left ||= 3
  end  

  def remove_vote
    self.votes_left -= 1
    self.save
  end  

 def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      # user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def show

    @students= Student.all.where(cohort_id: params[:id])
    p @students
    @cohort_name= @students.first.cohort_name
    p @cohort_name
  end  
end  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
end

app/controllers/session_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
    @user = User.find_or_create_from_auth_hash(auth_hash)
    self.current_user = @user
    redirect_to '/'
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
  	session.clear
  	redirect_to root_path
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
    @top_10 = @students.sort{|s2,s1| s1.student_points <=> s2.student_points}.first(10)
    
  end


  def show
    @student=Student.find(params[:id])
    @comments= @student.comments.reverse_order
  end


  def update
    

    if current_user
      if current_user.votes_left <= 0
          render :json => {:comment => "Dude buy some votes!"}
      else   
        @student =Student.find(params[:id])
        @comment = Comment.create(student_id: params[:id], body: params[:body])
        @comment.save 
        if @comment.save == false
          return render :json => {:comment => "Make it bigger!"}
        else
          @student.upvote
          current_user.remove_vote
          @student.save
          render :json => {:comment => @comment.body}           
        end  
      end
    end    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cohorts/show.html.erb
<ul class="cohort_members clearfix">
  <h1><%= @cohort_name %></h1>

  <% @students.each do |s| %>
    <li class="student_cluster">
      <%= image_tag(s.gravatar_url, class: "student_image") %>

      <div class="student_info">
        <span class="student_points"><%= s.student_points %></span>
        <h3 class="student_name"><%= link_to (s.name), student_path(s.id) %></h3>
        <div class="student_vote_show">
          <%= link_to "Give Point", student_path(s.id), class: "point_button" %>
        </div>
      </div>
    </li>
  <%end%>
</ul>

app/views/home/index.html.erb
  <% if current_user %>


    <div id="cohort_list">
      <h1 class="spirit_heading">Choose Your <span>Spirit Animal</span></h1>

      <%= link_to image_tag("nighthawks.jpg", class: "cohort_image"), cohort_path(26) %>
      <%= link_to image_tag("fireflies.jpg", class: "cohort_image"), cohort_path(28) %>
      <%= link_to image_tag("coyotes.jpg", class: "cohort_image"), cohort_path(30) %>
      <%= link_to image_tag("salamanders.jpg", class: "cohort_image"), cohort_path(32) %>
    </div>

  <% else %>

    <div class="inner">
      <div class="logo">
        <%= image_tag("40df87dd0e58743609507b50b7bd7e36.jpeg", class: "founders") %>
        <%= image_tag("70f916b724a80587af391696d03ddf8a.jpeg", class: "founders") %>
        <%= image_tag("685a7bcfc0fd1d4b4987e349b94c58f0.jpeg", class: "founders") %>
        <%= image_tag("d0b6ff8c91b4b453455d922e3b09b798.jpeg", class: "founders") %>
      </div>

      <h1 class="welcome_msg">Drop sciences. Get points.</span></h1>
      <p>Points can also be bought with Bitcoins.</p>
      <%= link_to "Sign In", "/auth/dbc", id: "sign_in" %>
    </div>

  <% end %>

app/views/home/show.html.erb
<h1>Welcome to DBC Power Rankings</h1>



<%= link_to ("NightHawks"), cohort_path(26) %>
<%= link_to ("FireFlies"), cohort_path(28) %>
<%= link_to ("Coyotes"), cohort_path(30) %>
<%= link_to ("Salamanders"), cohort_path(32) %>

app/views/layouts/_header.html.erb
<% if current_user %>
  <header>
    <a id="open_settings">open settings</a>

    <ul id="settings">
        <div class="setting_header">
          <a id="close_settings">Close</a>
          <h2>Settings</h2>
        </div>

        <li><%= link_to "Profile", student_path(Student.where(uid: current_user.uid).first), class: "setting_titles" %></li>
        <li><%= link_to "Leader Board", students_path, class: "setting_titles" %></li>
        <li><%= link_to "Contact Us", "http://google.com", class: "setting_titles" %></li>
        <li><%= link_to "Sign out", logout_path, id: "sign_out", class: "setting_titles" %></li>
    </ul>
  </header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcPower</title>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>
<% if current_user %>
  <body>
<% else %>
  <body class="front_page">
<% end %>
  <!-- following user-widget is for oauth  -->
  <%= render 'layouts/header' %>
  <%= yield %>
</body>
</html>

app/views/students/index.html.erb
	<ol>
	<h1>Leader Board</h1>
	<% @top_10.each do |student| %>
		<li><%= link_to student.name, student_path(student) %> from <%= link_to student.cohort_name, cohort_path(student.cohort_id) %> for has <%= student.student_points %> points.</li>
		<%= image_tag(student.gravatar_url) %>
	<% end %>
	</ol>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<ul class="info">

  <li><%= image_tag(@student.gravatar_url) %></li>
  <li><%= @student.email %></li>
  <li><%= @student.cohort_name %></li>
  <li><%= @student.student_points %></li>
  <a id="up_vote_button" href="/comment_vote">Up Vote Button</a>
  <li><%= @student.twitter %></li>

  <%= form_tag student_path(@student), :method => 'patch', :id => 'student'  do %>
   <%= text_field_tag(:body) %>
   <%= submit_tag("Submit") %>
<% end %>
</ul>
<ul class="comment">
  <%@comments.each do |c|%>
  <li><%=c.body%></li>
  <%end%>

</ul>

app/views/users/index.html.erb
<h3>Users:</h>

<% @users.each do |user| %>
<%= user.username  %><br>
<% end %>